FROM centos:centos7

MAINTAINER Constantinos Kouloumbris <c@kouloumbris.com>

RUN yum -y upgrade

RUN yum -y install \
    bash-completion \
    curl \
    hostname \
    vim-enhanced \
    git \
    supervisor

RUN yum clean all


